//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSS {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSS.src.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Solid State Sidebar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonApply {
            get {
                return ResourceManager.GetString("ButtonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonDone {
            get {
                return ResourceManager.GetString("ButtonDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GitHub に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonGitHub {
            get {
                return ResourceManager.GetString("ButtonGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonHide {
            get {
                return ResourceManager.GetString("ButtonHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonQuit {
            get {
                return ResourceManager.GetString("ButtonQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonReload {
            get {
                return ResourceManager.GetString("ButtonReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Revert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonRevert {
            get {
                return ResourceManager.GetString("ButtonRevert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonSettings {
            get {
                return ResourceManager.GetString("ButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonShow {
            get {
                return ResourceManager.GetString("ButtonShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonSkip {
            get {
                return ResourceManager.GetString("ButtonSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonUpdate {
            get {
                return ResourceManager.GetString("ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visibility に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonVisibility {
            get {
                return ResourceManager.GetString("ButtonVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CPU に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CPU {
            get {
                return ResourceManager.GetString("CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clock に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CPUClock {
            get {
                return ResourceManager.GetString("CPUClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clock に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CPUClockLabel {
            get {
                return ResourceManager.GetString("CPUClockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Core Clock に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CPUCoreClock {
            get {
                return ResourceManager.GetString("CPUCoreClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Core に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CPUCoreClockLabel {
            get {
                return ResourceManager.GetString("CPUCoreClockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Core Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CPUCoreLoad {
            get {
                return ResourceManager.GetString("CPUCoreLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Core に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CPUCoreLoadLabel {
            get {
                return ResourceManager.GetString("CPUCoreLoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fan Usage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CPUFan {
            get {
                return ResourceManager.GetString("CPUFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Fan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CPUFanLabel {
            get {
                return ResourceManager.GetString("CPUFanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CPULoad {
            get {
                return ResourceManager.GetString("CPULoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CPULoadLabel {
            get {
                return ResourceManager.GetString("CPULoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CPUTemp {
            get {
                return ResourceManager.GetString("CPUTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CPUTempLabel {
            get {
                return ResourceManager.GetString("CPUTempLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voltage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CPUVoltage {
            get {
                return ResourceManager.GetString("CPUVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CPUVoltageLabel {
            get {
                return ResourceManager.GetString("CPUVoltageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DateDisabled {
            get {
                return ResourceManager.GetString("DateDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Long に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DateLong {
            get {
                return ResourceManager.GetString("DateLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DateNormal {
            get {
                return ResourceManager.GetString("DateNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Short に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DateShort {
            get {
                return ResourceManager.GetString("DateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Free に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DriveFree {
            get {
                return ResourceManager.GetString("DriveFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Free に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DriveFreeLabel {
            get {
                return ResourceManager.GetString("DriveFreeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DriveLoad {
            get {
                return ResourceManager.GetString("DriveLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load Bar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DriveLoadBar {
            get {
                return ResourceManager.GetString("DriveLoadBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DriveLoadBarLabel {
            get {
                return ResourceManager.GetString("DriveLoadBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DriveLoadLabel {
            get {
                return ResourceManager.GetString("DriveLoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read Rate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DriveRead {
            get {
                return ResourceManager.GetString("DriveRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DriveReadLabel {
            get {
                return ResourceManager.GetString("DriveReadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drives に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Drives {
            get {
                return ResourceManager.GetString("Drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Used に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DriveUsed {
            get {
                return ResourceManager.GetString("DriveUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Used に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DriveUsedLabel {
            get {
                return ResourceManager.GetString("DriveUsedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write Rate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DriveWrite {
            get {
                return ResourceManager.GetString("DriveWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Writ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DriveWriteLabel {
            get {
                return ResourceManager.GetString("DriveWriteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your Performance Counter cache is corrupted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorPerformanceCounter {
            get {
                return ResourceManager.GetString("ErrorPerformanceCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sidebar Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GitHub に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GPU に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GPU {
            get {
                return ResourceManager.GetString("GPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Core Clock に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GPUCoreClock {
            get {
                return ResourceManager.GetString("GPUCoreClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Core に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GPUCoreClockLabel {
            get {
                return ResourceManager.GetString("GPUCoreClockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Core Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GPUCoreLoad {
            get {
                return ResourceManager.GetString("GPUCoreLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GPUCoreLoadLabel {
            get {
                return ResourceManager.GetString("GPUCoreLoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fan Usage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GPUFan {
            get {
                return ResourceManager.GetString("GPUFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Fan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GPUFanLabel {
            get {
                return ResourceManager.GetString("GPUFanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GPUTemp {
            get {
                return ResourceManager.GetString("GPUTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GPUTempLabel {
            get {
                return ResourceManager.GetString("GPUTempLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voltage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GPUVoltage {
            get {
                return ResourceManager.GetString("GPUVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GPUVoltageLabel {
            get {
                return ResourceManager.GetString("GPUVoltageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VRAM Clock に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GPUVRAMClock {
            get {
                return ResourceManager.GetString("GPUVRAMClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VRAM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GPUVRAMClockLabel {
            get {
                return ResourceManager.GetString("GPUVRAMClockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VRAM Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GPUVRAMLoad {
            get {
                return ResourceManager.GetString("GPUVRAMLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VRAM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GPUVRAMLoadLabel {
            get {
                return ResourceManager.GetString("GPUVRAMLoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please restart the app. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageChangedText {
            get {
                return ResourceManager.GetString("LanguageChangedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language Changed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageChangedTitle {
            get {
                return ResourceManager.GetString("LanguageChangedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   External IP Address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkExtIP {
            get {
                return ResourceManager.GetString("NetworkExtIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ext に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkExtIPLabel {
            get {
                return ResourceManager.GetString("NetworkExtIPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bandwidth In に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkIn {
            get {
                return ResourceManager.GetString("NetworkIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///    In に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkInLabel {
            get {
                return ResourceManager.GetString("NetworkInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP Address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkIP {
            get {
                return ResourceManager.GetString("NetworkIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///    IP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkIPLabel {
            get {
                return ResourceManager.GetString("NetworkIPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bandwidth Out に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkOut {
            get {
                return ResourceManager.GetString("NetworkOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Out に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkOutLabel {
            get {
                return ResourceManager.GetString("NetworkOutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RAM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RAM {
            get {
                return ResourceManager.GetString("RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clock に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RAMClock {
            get {
                return ResourceManager.GetString("RAMClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clock に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RAMClockLabel {
            get {
                return ResourceManager.GetString("RAMClockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Free に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RAMFree {
            get {
                return ResourceManager.GetString("RAMFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Free に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RAMFreeLabel {
            get {
                return ResourceManager.GetString("RAMFreeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RAMLoad {
            get {
                return ResourceManager.GetString("RAMLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RAMLoadLabel {
            get {
                return ResourceManager.GetString("RAMLoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Used に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RAMUsed {
            get {
                return ResourceManager.GetString("RAMUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Used に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RAMUsedLabel {
            get {
                return ResourceManager.GetString("RAMUsedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voltage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RAMVoltage {
            get {
                return ResourceManager.GetString("RAMVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voltage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RAMVoltageLabel {
            get {
                return ResourceManager.GetString("RAMVoltageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   24 Hour Clock に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings24HourClock {
            get {
                return ResourceManager.GetString("Settings24HourClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changes the clock&apos;s time format to 24 hours. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings24HourClockTooltip {
            get {
                return ResourceManager.GetString("Settings24HourClockTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Advanced に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsAdvancedTab {
            get {
                return ResourceManager.GetString("SettingsAdvancedTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alert Blink に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsAlertBlink {
            get {
                return ResourceManager.GetString("SettingsAlertBlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Makes the alert text blink. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsAlertBlinkTooltip {
            get {
                return ResourceManager.GetString("SettingsAlertBlinkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alert Font Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsAlertFontColor {
            get {
                return ResourceManager.GetString("SettingsAlertFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color of alert text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsAlertFontColorTooltip {
            get {
                return ResourceManager.GetString("SettingsAlertFontColorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show All Core Clocks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsAllCoreClocks {
            get {
                return ResourceManager.GetString("SettingsAllCoreClocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shows the clock speeds of all cores not just the first. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsAllCoreClocksTooltip {
            get {
                return ResourceManager.GetString("SettingsAllCoreClocksTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always On Top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsAlwaysOnTop {
            get {
                return ResourceManager.GetString("SettingsAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Makes the sidebar always on top of other windows. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsAlwaysOnTopTooltip {
            get {
                return ResourceManager.GetString("SettingsAlwaysOnTopTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsAutoUpdate {
            get {
                return ResourceManager.GetString("SettingsAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updates the app automatically. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsAutoUpdateTooltip {
            get {
                return ResourceManager.GetString("SettingsAutoUpdateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsBackgroundColor {
            get {
                return ResourceManager.GetString("SettingsBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color of the background. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsBackgroundColorTooltip {
            get {
                return ResourceManager.GetString("SettingsBackgroundColorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background Opacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsBackgroundOpacity {
            get {
                return ResourceManager.GetString("SettingsBackgroundOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opacity of the background. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsBackgroundOpacityTooltip {
            get {
                return ResourceManager.GetString("SettingsBackgroundOpacityTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bandwidth In Alert: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsBandwidthInAlert {
            get {
                return ResourceManager.GetString("SettingsBandwidthInAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The kbps or kBps threshold at which bandwidth received alerts occur. Use 0 to disable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsBandwidthInAlertTooltip {
            get {
                return ResourceManager.GetString("SettingsBandwidthInAlertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bandwidth Out Alert: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsBandwidthOutAlert {
            get {
                return ResourceManager.GetString("SettingsBandwidthOutAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The kbps or kBps threshold at which bandwidth sent alerts occur. Use 0 to disable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsBandwidthOutAlertTooltip {
            get {
                return ResourceManager.GetString("SettingsBandwidthOutAlertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click Through に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsClickThrough {
            get {
                return ResourceManager.GetString("SettingsClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Makes mouse events pass through the window. Note this will prevent any interaction with the sidebar. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsClickThroughTooltip {
            get {
                return ResourceManager.GetString("SettingsClickThroughTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collapse Menu Bar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsCollapseMenuBar {
            get {
                return ResourceManager.GetString("SettingsCollapseMenuBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Removes the extra space at the top of the sidebar. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsCollapseMenuBarTooltip {
            get {
                return ResourceManager.GetString("SettingsCollapseMenuBarTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Core Loads に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsCoreLoads {
            get {
                return ResourceManager.GetString("SettingsCoreLoads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shows the percentage load of all cores. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsCoreLoadsTooltip {
            get {
                return ResourceManager.GetString("SettingsCoreLoadsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsCustomizeTab {
            get {
                return ResourceManager.GetString("SettingsCustomizeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date Font Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsDateFontSize {
            get {
                return ResourceManager.GetString("SettingsDateFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adjust the font size for the date display に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsDateFontSizeTooltip {
            get {
                return ResourceManager.GetString("SettingsDateFontSizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsDateFormat {
            get {
                return ResourceManager.GetString("SettingsDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsDateFormatDisabled {
            get {
                return ResourceManager.GetString("SettingsDateFormatDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format of the date below the clock. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsDateFormatTooltip {
            get {
                return ResourceManager.GetString("SettingsDateFormatTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dock に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsDock {
            get {
                return ResourceManager.GetString("SettingsDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsDockBottom {
            get {
                return ResourceManager.GetString("SettingsDockBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsDockLeft {
            get {
                return ResourceManager.GetString("SettingsDockLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsDockRight {
            get {
                return ResourceManager.GetString("SettingsDockRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Which edge the sidebar will dock to. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsDockTooltip {
            get {
                return ResourceManager.GetString("SettingsDockTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsDockTop {
            get {
                return ResourceManager.GetString("SettingsDockTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shows extra drive details as text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsDriveDetailsTooltip {
            get {
                return ResourceManager.GetString("SettingsDriveDetailsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsFontColor {
            get {
                return ResourceManager.GetString("SettingsFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color of text and icons. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsFontColorTooltip {
            get {
                return ResourceManager.GetString("SettingsFontColorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Family に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsFontName {
            get {
                return ResourceManager.GetString("SettingsFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font family of text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsFontNameTooltip {
            get {
                return ResourceManager.GetString("SettingsFontNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsFontSize {
            get {
                return ResourceManager.GetString("SettingsFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size of text and icons. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsFontSizeTooltip {
            get {
                return ResourceManager.GetString("SettingsFontSizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsGeneralTab {
            get {
                return ResourceManager.GetString("SettingsGeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsHardwareColumn1 {
            get {
                return ResourceManager.GetString("SettingsHardwareColumn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hardware (Editable) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsHardwareColumn2 {
            get {
                return ResourceManager.GetString("SettingsHardwareColumn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enables this hardware. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsHardwareEnabledTooltip {
            get {
                return ResourceManager.GetString("SettingsHardwareEnabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit the name of this hardware. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsHardwareNameTooltip {
            get {
                return ResourceManager.GetString("SettingsHardwareNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Header Style に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsHeaderStyle {
            get {
                return ResourceManager.GetString("SettingsHeaderStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsHeaderStyleDefault {
            get {
                return ResourceManager.GetString("SettingsHeaderStyleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsHeaderStyleNone {
            get {
                return ResourceManager.GetString("SettingsHeaderStyleNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Small に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsHeaderStyleSmall {
            get {
                return ResourceManager.GetString("SettingsHeaderStyleSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Horizontal Offset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsHorizontalOffset {
            get {
                return ResourceManager.GetString("SettingsHorizontalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Horizontal offset of the sidebar. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsHorizontalOffsetTooltip {
            get {
                return ResourceManager.GetString("SettingsHorizontalOffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsHotkeyClose {
            get {
                return ResourceManager.GetString("SettingsHotkeyClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch Edge に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsHotkeyCycleEdge {
            get {
                return ResourceManager.GetString("SettingsHotkeyCycleEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch Screen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsHotkeyCycleScreen {
            get {
                return ResourceManager.GetString("SettingsHotkeyCycleScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsHotkeyHide {
            get {
                return ResourceManager.GetString("SettingsHotkeyHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsHotkeyReload {
            get {
                return ResourceManager.GetString("SettingsHotkeyReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reserve Space に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsHotkeyReserveSpace {
            get {
                return ResourceManager.GetString("SettingsHotkeyReserveSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsHotkeyShow {
            get {
                return ResourceManager.GetString("SettingsHotkeyShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hotkeys に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsHotkeysTab {
            get {
                return ResourceManager.GetString("SettingsHotkeysTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsHotkeyToggle {
            get {
                return ResourceManager.GetString("SettingsHotkeyToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon Theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsIconTheme {
            get {
                return ResourceManager.GetString("SettingsIconTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide at Startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsInitiallyHidden {
            get {
                return ResourceManager.GetString("SettingsInitiallyHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Makes the sidebar hide at startup. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsInitiallyHiddenTooltip {
            get {
                return ResourceManager.GetString("SettingsInitiallyHiddenTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsLanguageDefault {
            get {
                return ResourceManager.GetString("SettingsLanguageDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current language of the app. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsLanguageTooltip {
            get {
                return ResourceManager.GetString("SettingsLanguageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Metrics: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsMetrics {
            get {
                return ResourceManager.GetString("SettingsMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Metrics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsMetricsColumnHeader {
            get {
                return ResourceManager.GetString("SettingsMetricsColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Label (Editable) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsMetricsLabelColumn {
            get {
                return ResourceManager.GetString("SettingsMetricsLabelColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit labels to customize the display に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsMetricsLabelTooltip {
            get {
                return ResourceManager.GetString("SettingsMetricsLabelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t Wrap Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsMetricsNoWrap {
            get {
                return ResourceManager.GetString("SettingsMetricsNoWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prevents text from wrapping to the next line. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsMetricsNoWrapTooltip {
            get {
                return ResourceManager.GetString("SettingsMetricsNoWrapTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore default label に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsMetricsResetLabelTooltip {
            get {
                return ResourceManager.GetString("SettingsMetricsResetLabelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click to change the order or labels of the metrics. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsMetricsTooltip {
            get {
                return ResourceManager.GetString("SettingsMetricsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enables this module. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsMonitorEnabledTooltip {
            get {
                return ResourceManager.GetString("SettingsMonitorEnabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsMonitorsColumn1 {
            get {
                return ResourceManager.GetString("SettingsMonitorsColumn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modules に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsMonitorsColumn2 {
            get {
                return ResourceManager.GetString("SettingsMonitorsColumn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click a row to edit its settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsMonitorsSubtitle1 {
            get {
                return ResourceManager.GetString("SettingsMonitorsSubtitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drag a row to change its order. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsMonitorsSubtitle2 {
            get {
                return ResourceManager.GetString("SettingsMonitorsSubtitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modules に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsMonitorsTab {
            get {
                return ResourceManager.GetString("SettingsMonitorsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Polling Interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPollingInterval {
            get {
                return ResourceManager.GetString("SettingsPollingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time between polling for data in milliseconds. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPollingIntervalTooltip {
            get {
                return ResourceManager.GetString("SettingsPollingIntervalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reserve Space に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsReserveSpace {
            get {
                return ResourceManager.GetString("SettingsReserveSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reserves space in the work area for the sidebar. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsReserveSpaceTooltip {
            get {
                return ResourceManager.GetString("SettingsReserveSpaceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Round All Decimals に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsRoundAllDecimals {
            get {
                return ResourceManager.GetString("SettingsRoundAllDecimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Round all decimal values to the nearest integer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsRoundAllDecimalsTooltip {
            get {
                return ResourceManager.GetString("SettingsRoundAllDecimalsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run at Startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsRunAtStartup {
            get {
                return ResourceManager.GetString("SettingsRunAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Runs the app when you first log in. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsRunAtStartupTooltip {
            get {
                return ResourceManager.GetString("SettingsRunAtStartupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Screen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsScreen {
            get {
                return ResourceManager.GetString("SettingsScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Which screen the sidebar will be on. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsScreenTooltip {
            get {
                return ResourceManager.GetString("SettingsScreenTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Clock に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsShowClock {
            get {
                return ResourceManager.GetString("SettingsShowClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shows the clock. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsShowClockTooltip {
            get {
                return ResourceManager.GetString("SettingsShowClockTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsShowDate {
            get {
                return ResourceManager.GetString("SettingsShowDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show the date in the time module に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsShowDateTooltip {
            get {
                return ResourceManager.GetString("SettingsShowDateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Drive Details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsShowDriveDetails {
            get {
                return ResourceManager.GetString("SettingsShowDriveDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Drive IO に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsShowDriveIO {
            get {
                return ResourceManager.GetString("SettingsShowDriveIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shows drive read and write speeds if drive details is enabled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsShowDriveIOTooltip {
            get {
                return ResourceManager.GetString("SettingsShowDriveIOTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Drive Space に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsShowDriveSpace {
            get {
                return ResourceManager.GetString("SettingsShowDriveSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shows load percent, used space, and free space if drive details is enabled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsShowDriveSpaceTooltip {
            get {
                return ResourceManager.GetString("SettingsShowDriveSpaceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Hardware Names に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsShowHardwareNames {
            get {
                return ResourceManager.GetString("SettingsShowHardwareNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shows hardware names. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsShowHardwareNamesTooltip {
            get {
                return ResourceManager.GetString("SettingsShowHardwareNamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show PC Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsShowMachineName {
            get {
                return ResourceManager.GetString("SettingsShowMachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shows the name of the computer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsShowMachineNameTooltip {
            get {
                return ResourceManager.GetString("SettingsShowMachineNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsShowTime {
            get {
                return ResourceManager.GetString("SettingsShowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show the time in the time module に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsShowTimeTooltip {
            get {
                return ResourceManager.GetString("SettingsShowTimeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Tray Icon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsShowTrayIcon {
            get {
                return ResourceManager.GetString("SettingsShowTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shows the tray icon in the taskbar. This is sometimes required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsShowTrayIconTooltip {
            get {
                return ResourceManager.GetString("SettingsShowTrayIconTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sidebar Margin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsSidebarMargin {
            get {
                return ResourceManager.GetString("SettingsSidebarMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adjust the horizontal margin of the sidebar content に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsSidebarMarginTooltip {
            get {
                return ResourceManager.GetString("SettingsSidebarMarginTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sidebar Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsSidebarWidth {
            get {
                return ResourceManager.GetString("SettingsSidebarWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Width of the sidebar in pixels. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsSidebarWidthTooltip {
            get {
                return ResourceManager.GetString("SettingsSidebarWidthTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature Alert: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsTemperatureAlert {
            get {
                return ResourceManager.GetString("SettingsTemperatureAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The temperature threshold at which alerts occur. Use 0 to disable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsTemperatureAlertTooltip {
            get {
                return ResourceManager.GetString("SettingsTemperatureAlertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text Align に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsTextAlign {
            get {
                return ResourceManager.GetString("SettingsTextAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsTextAlignLeft {
            get {
                return ResourceManager.GetString("SettingsTextAlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsTextAlignRight {
            get {
                return ResourceManager.GetString("SettingsTextAlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alignment of metric text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsTextAlignTooltip {
            get {
                return ResourceManager.GetString("SettingsTextAlignTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time Font Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsTimeFontSize {
            get {
                return ResourceManager.GetString("SettingsTimeFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adjust the font size for the time display に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsTimeFontSizeTooltip {
            get {
                return ResourceManager.GetString("SettingsTimeFontSizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sidebar Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toolbar Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsToolbarMode {
            get {
                return ResourceManager.GetString("SettingsToolbarMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hides the sidebar in alt-tab and makes it persist between virtual desktops. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsToolbarModeTooltip {
            get {
                return ResourceManager.GetString("SettingsToolbarModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UI Scale に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsUIScale {
            get {
                return ResourceManager.GetString("SettingsUIScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scale of Sidebar UI components. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsUIScaleTooltip {
            get {
                return ResourceManager.GetString("SettingsUIScaleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Bytes Per Second に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsUseBytesPerSecond {
            get {
                return ResourceManager.GetString("SettingsUseBytesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shows bandwidth in bytes instead of bits per second. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsUseBytesPerSecondTooltip {
            get {
                return ResourceManager.GetString("SettingsUseBytesPerSecondTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Used Space Alert: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsUsedSpaceAlert {
            get {
                return ResourceManager.GetString("SettingsUsedSpaceAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The percentage threshold at which used space alerts occur. Use 0 to disable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsUsedSpaceAlertTooltip {
            get {
                return ResourceManager.GetString("SettingsUsedSpaceAlertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Fahrenheit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsUseFahrenheit {
            get {
                return ResourceManager.GetString("SettingsUseFahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperatures for sensors and alerts will be in Fahrenheit instead of Celsius. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsUseFahrenheitTooltip {
            get {
                return ResourceManager.GetString("SettingsUseFahrenheitTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use GHz に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsUseGHz {
            get {
                return ResourceManager.GetString("SettingsUseGHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clock speeds will be in GHz instead of MHz. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsUseGHzTooltip {
            get {
                return ResourceManager.GetString("SettingsUseGHzTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vertical Offset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsVerticalOffset {
            get {
                return ResourceManager.GetString("SettingsVerticalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vertical offset of the sidebar. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsVerticalOffsetTooltip {
            get {
                return ResourceManager.GetString("SettingsVerticalOffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Virtual Desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsVirtualDesktop {
            get {
                return ResourceManager.GetString("SettingsVirtualDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enables support for virtual desktops. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsVirtualDesktopTooltip {
            get {
                return ResourceManager.GetString("SettingsVirtualDesktopTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use the sliders and textboxes to move the sidebar to the correct position. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupCustomSubtitle {
            get {
                return ResourceManager.GetString("SetupCustomSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupCustomTitle {
            get {
                return ResourceManager.GetString("SetupCustomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you want to customize the sidebar click the settings button. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupDoneSubtitle {
            get {
                return ResourceManager.GetString("SetupDoneSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can also access the settings via the gear icon at the top-right of the sidebar or via the tray icon in the taskbar. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupDoneText {
            get {
                return ResourceManager.GetString("SetupDoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupDoneTitle {
            get {
                return ResourceManager.GetString("SetupDoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is a quick setup to get the sidebar in the correct position. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupSubtitle {
            get {
                return ResourceManager.GetString("SetupSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is the sidebar visible and docked to the right edge of your primary monitor? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupText {
            get {
                return ResourceManager.GetString("SetupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initial Setup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetupTitle {
            get {
                return ResourceManager.GetString("SetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Day of Week に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShowDayOfWeek {
            get {
                return ResourceManager.GetString("ShowDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display the day of the week (e.g. Mon, Tue) after the date. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShowDayOfWeekTooltip {
            get {
                return ResourceManager.GetString("ShowDayOfWeekTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sidebar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sidebar {
            get {
                return ResourceManager.GetString("Sidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimeLabel {
            get {
                return ResourceManager.GetString("TimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A fatal error occurred while trying to update. Auto update is now disabled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateErrorFatalText {
            get {
                return ResourceManager.GetString("UpdateErrorFatalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to update. Check your internet connection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateErrorText {
            get {
                return ResourceManager.GetString("UpdateErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateErrorTitle {
            get {
                return ResourceManager.GetString("UpdateErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You have the latest version. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateSuccessText {
            get {
                return ResourceManager.GetString("UpdateSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
    }
}
